// <auto-generated />
using System;
using GestionSolicitudes.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionSolicitudes.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260807181527_SincronizarColumnas")]
    partial class SincronizarColumnas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionSolicitudes.Domain.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Solicitante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Solicitudes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "",
                            Estado = 1,
                            FechaCreacion = new DateTime(2026, 8, 7, 18, 15, 26, 738, DateTimeKind.Utc).AddTicks(3959),
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Solicitante = "Elys Camila Batista Encarnacion ",
                            Titulo = "Instalación de equipo"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "",
                            Estado = 1,
                            FechaCreacion = new DateTime(2026, 8, 7, 18, 15, 26, 738, DateTimeKind.Utc).AddTicks(3962),
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Solicitante = "Pedro Martinez Gonzales ",
                            Titulo = "Mantenimiento de software"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "",
                            Estado = 1,
                            FechaCreacion = new DateTime(2026, 8, 7, 18, 15, 26, 738, DateTimeKind.Utc).AddTicks(3963),
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Solicitante = "Leonel Leon Pica piedra  ",
                            Titulo = "Actualización de sistema"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "",
                            Estado = 1,
                            FechaCreacion = new DateTime(2026, 8, 7, 18, 15, 26, 738, DateTimeKind.Utc).AddTicks(3964),
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Solicitante = "Giana pichardo Chiguaua ",
                            Titulo = " Revision de Red "
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Descripcion = "",
                            Estado = 1,
                            FechaCreacion = new DateTime(2026, 8, 7, 18, 15, 26, 738, DateTimeKind.Utc).AddTicks(3965),
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Solicitante = " Rossi Mosqueta Garcia",
                            Titulo = " Actualizacion de licenias "
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
